### ISSUE TITLE
Integration with Tasks/Decks: Smartlink should be able to render selected table row

### ISSUE THREAD

**Issue by chrda81** [nextcloud/tables#630] opened 2023-10-21 20:17 UTC
### Describe the solution you'd like

I'm trying to use Tables as list for project management, e.g. as backlog. In the Decks app I can use smartlinks to render a selected table as link or content. It would be nice, if I could pick a row instead of showing the whole content, so I can reference this single backlog item.

### Describe alternatives you've considered

I created a table view and add the meta ID, but it isn't visible in the Smartlink render mode *content*, when adding this to a Decks card. I thought I could show the content, then modify the Smartlink to something like ../apps/tables/#/table/12/row/{ID}, but this link is not possible

**Comment by juliushaertl** [comment] 2023-10-23 07:24
Thanks for the suggestion. This is actually a duplicate of https://github.com/nextcloud/tables/issues/579 so I'll close this in favor of the other one.

**Closed by juliushaertl** 2023-10-23 07:24 UTC
Labels: enhancement, 0. Needs triage
