### ISSUE TITLE
Unable to select Contacts in a column field

### ISSUE THREAD

**Issue by BlueBeezzzz** [nextcloud/tables#831] opened 2024-02-08 16:42 UTC
### Steps to reproduce

1. Create a table
2. Create a column to select a value
3. Select Contacts in 'Allow Types'

### Expected behavior

Expecting when adding a row in the table to be able select to selecty a contact in NC 

### Actual behavior

Not be able to select a Nextcloud Contact

### Tables app version

0.6.6

### Browser

FireFox, Edge, Chrome

### Client operating system

Windows, Linux

### Operating system

Ubuntu 22.04.3 LTS, Nextcloud v28.0.2

### Web server

Apache

### PHP engine version

PHP 8.1

### Database

MariaDB

**Comment by enjeck** [comment] 2024-02-16 07:46
Hi @BlueBeezzzz . I'm trying to reproduce this. Please explain steps 2 and 3 in detail

**Comment by BlueBeezzzz** [comment] 2024-02-16 15:03
> Hi @BlueBeezzzz . I'm trying to reproduce this. Please explain steps 2 and 3 in detail

Hi @enjeck, 
Let us say I want to create a table of tasks that I want to relate to users in the company. Then I create a table with (for this example) two columns:

1. the Description of the task
2. the User to is responsible for the task.

The issue is that the column for the User is not working. To do so you edit the column set the ´allow types´ for the column to Contacts. Then when you are trying the table and create a new record, you can type whaatever you want in the User filed, but no Contact details show up. So no User can be selected here.

Conclusion is that the Contacts as 'Allowed Types' for a column is not working.
Hope this explains the issue a bit more clear.

**Comment by enjeck** [comment] 2024-02-19 05:03
> 2\. the User to is responsible for the task.

What column type are you using for this?

**Comment by enjeck** [comment] 2024-02-19 05:57
@juliushaertl The `Contacts` provider is now [unavailable by default](https://github.com/nextcloud/tables/commit/a32ca26616accb88bbfdeda9e76b9f7c0f2a4711), so I can't even reproduce this issue since the option doesn't how up in "Allowed Types". How can I somehow "enable" it.

**Comment by juliushaertl** [comment] 2024-02-20 09:54
you need to have the contacts app enabled for that iirc 


https://github.com/nextcloud/contacts

**Comment by BlueBeezzzz** [comment] 2024-02-20 13:47
Ahen you create a table from scratch and you are creating a 'Custom table', then create a column set column type to 'LINK'.

The option to shoose allow type will show up and you will see various to select. The third option is Contacts and is selected by default.

But when trying the new table, you can type whatever you want in the column, but ni contact information can be selected.
I am using NC 28.0.2, table version 0.6.6 and Contacts version 5.5.2, Contacts Interaction 1.9.0

**Comment by Aveyron-RetD** [comment] 2024-02-22 14:46
I confirm the bug.

**Comment by tbousiou** [comment] 2024-04-02 12:39
I am not able to select contacts from the system address book that contains users. For normal contacts it works.
Nextcloud 27.1.8

**Comment by JackyBull** [comment] 2024-04-03 10:56
Reproducable (as tbousiou described it) on NC 28.0.4 as well

**Comment by enjeck** [comment] 2024-04-03 13:03
I looked into this, and it's not really a Tables problem. The search provider no longer gives the system address book. I'll check with the devs over there if this is intentional and if there's another way to get them

**Comment by JackyBull** [comment] 2024-04-03 14:05
> I looked into this, and it's not really a Tables problem. The contacts search provider no longer gives the system address book. I'll check with the devs over there if this is intentional and if there's another way to get them

Yes, that's true. For instance you can't add Users to contact groups, but only contacts that are not users.

**Comment by enjeck** [comment] 2024-04-05 10:24
So, this is a feature, not a bug. The search provider does not support the system address book, just normal contact.  There's an [issue here tracking the feature request](https://github.com/nextcloud/server/issues/44669) to add support for this. 

Closing this since it's not a Tables problem.

**Closed by enjeck** 2024-04-05 10:24 UTC
Labels: bug, 0. Needs triage
