### ISSUE TITLE
Tables 0.7.0. Applications could not been created.

### ISSUE THREAD

**Issue by Jednadvacet** [nextcloud/tables#1005] opened 2024-04-26 07:50 UTC
### Steps to reproduce

1. Tables 0.7.0. 
2. Create Application
3. Fill inputs

### Expected behavior

No-code app is created.

### Actual behavior

No app created. NC says "App could not been created" error, progress wheel rotating.

### Tables app version

0.7.0.

### Browser

Edge

### Operating system

Ubuntu 20.04

### Web server

Nginx

### PHP engine version

PHP 8.1

### Database

MySQL

### Additional info

Log output:
```
Exception
OCA\Tables\Controller\ContextController::create(): Argument #2 ($iconName) must be of type string, array given, called in /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 232 in file '/var/www/html/nextcloud/apps/tables/lib/Controller/ContextController.php' line 97
```

**Comment by blizzz** [comment] 2024-04-26 07:54
Duplicate of https://github.com/nextcloud/tables/issues/1000 and fixed on git (not yet released). As workaround: pick an icon when creating it.

**Closed by blizzz** 2024-04-26 07:54 UTC
Labels: bug, 0. Needs triage

**Comment by Jednadvacet** [comment] 2024-04-26 07:56
Excellent. Thanks!
