### ISSUE TITLE
Reorder columns

### ISSUE THREAD

**Issue by niclasheinz** [nextcloud/tables#980] opened 2024-04-14 13:20 UTC
### Is your feature request related to a problem? Please describe.

After I insert different columns into a newly created table, the order of the columns  changes without me wanting it to. This only happens with one out of 10 columns.

### Describe the solution you'd like

I would like to be able to click on the three dots for each column so that I can change the order of the columns later. I can either move the column one to the left or one to the right.

**Comment by enjeck** [comment] 2024-04-14 13:34
Duplicate of https://github.com/nextcloud/tables/issues/607

**Closed by enjeck** 2024-04-14 13:34 UTC
Labels: enhancement, 0. Needs triage
