### ISSUE TITLE
Ability to rearrange columns.

### ISSUE THREAD

**Issue by baditaflorin** [nextcloud/tables#1265] opened 2024-08-03 20:42 UTC
### Is your feature request related to a problem? Please describe.

Currently let's say i want to create a start and end column, and i create the start and then i create 2 other column and olnly after i remember i wanted a end column. the end column will be at the end and the start in another part.

### Describe the solution you'd like

Ability to rearrange columns on the fly

**Comment by juliushaertl** [comment] 2024-08-05 15:51
Thanks for your suggestion. Closing as a duplicate of https://github.com/nextcloud/tables/issues/607. Please check if there are already existing issues next time :)

**Closed by juliushaertl** 2024-08-05 15:51 UTC
Labels: enhancement, 0. Needs triage
