### ISSUE TITLE
Long, ellipsized cells should show full text on hover

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/tables#1068] opened 2024-05-06 09:41 UTC
### Steps to reproduce

1. Create a table
2. Add a row with long text
3. Look at the table view
4. Hover ellipsized cells

### Expected behavior

I see the full text

### Actual behavior

![image](https://github.com/nextcloud/tables/assets/1374172/b64fdb9f-e7bc-4788-aa99-2239b77fca94)

I have to click the row to see the rest.

### Web server

None

### PHP engine version

None

### Database

None

**Comment by enjeck** [comment] 2024-05-06 10:36
Duplicate of #974

**Closed by enjeck** 2024-05-06 10:36 UTC
Labels: bug, 0. Needs triage, accessibility
