### ISSUE TITLE
Table total rows not updated upon add/delete row

### ISSUE THREAD

**Issue by whisperdancer** [nextcloud/tables#731] opened 2023-12-04 00:34 UTC
### Steps to reproduce

1. Open a table
2. Add or delete a row
3. Hover over the table name in left pane and it doesn't change to reflect the change

### Expected behavior

After adding or deleting a row in a table, when hovering over the table name I expect the total rows to update to reflect the change.

### Actual behavior

1. Open a table
2. Add or delete a row
3. Hover over the table name in left pane and the total rows doesn't change to reflect the change

### Tables app version

0.6.4

### Browser

firefox 120.0.1

### Client operating system

Win 10

### Operating system

RaspberryPi OS 64bit

### Web server

Nginx

### PHP engine version

PHP 8.2

### Database

MariaDB

**Comment by juliushaertl** [comment] 2024-01-19 08:23
Thanks for reporting. Closing as a duplicate of https://github.com/nextcloud/tables/issues/451

**Closed as not planned by juliushaertl** 2024-01-19 08:23 UTC
Labels: bug, 0. Needs triage
