### ISSUE TITLE
Ability to clone row

### ISSUE THREAD

**Issue by baditaflorin** [nextcloud/tables#1266] opened 2024-08-03 20:48 UTC
### Is your feature request related to a problem? Please describe.

Let's say I created a row entry, and I want to create another copy of that row and ust modify one or 2 values, currently I need to create a new row and add all the data again, even in some use-cases I would need just to change the value of a single column

### Describe the solution you'd like

When selecting a row, have a duplicate feature that will duplicate the row.

**Comment by juliushaertl** [comment] 2024-08-05 15:50
Closing as a duplicate of https://github.com/nextcloud/tables/issues/69

**Closed by juliushaertl** 2024-08-05 15:50 UTC
Labels: enhancement, 0. Needs triage
