### ISSUE TITLE
FR: make certain columns readonly inside a view

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/tables#591] opened 2023-09-20 12:52 UTC
### Is your feature request related to a problem? Please describe.

At the moment, read/write permission is only available on a view level, not a column/field level.

### Describe the solution you'd like

e.g. for a vacation request process.
I want the employee to submit a vacation request (from, to, number of days)
I want the HR to approve (yes/no, who approved, when). But I don't want the HR to modify the initial fields (from, to, number of days)

### Describe alternatives you've considered

create several views allowing access to different rows.
in that situation, HR could see the request details in a certain view, and approve it in another one, which will be difficult.

**Comment by enjeck** [comment] 2024-02-16 06:56
Duplicate of https://github.com/nextcloud/tables/issues/591

**Comment by maximelehericy** [comment] 2024-02-19 14:17
@enjeck hi cleopatra, this is a pretty unusual way of closing issues :) marking an issue as duplicate of itself 😛
was that an error ?

**Closed** 2024-02-20 09:59 UTC
Labels: enhancement, 0. Needs triage
