### ISSUE TITLE
Can't erase table

### ISSUE THREAD

**Issue by barbayellow** [nextcloud/tables#1188] opened 2024-07-09 12:48 UTC
### Steps to reproduce

1. Create a table using web interface
2. Try to erase it using occ:tables:erase id
3. Get an error : `OCA\Tables\Db\Row2Mapper::getFilterExpression(): Argument #2 ($column) must be of type OCA\Tables\Db\Column, null given`
4. Can't create any more tables

### Expected behavior

The table should be erased and new tables should be able to be created

### Actual behavior

When trying to erase a table using  using occ:tables:erase tableid, I get stuck with an error : 
OCA\Tables\Db\Row2Mapper::getFilterExpression(): Argument #2 ($column) must be of type OCA\Tables\Db\Column, null given

### Tables app version

0.7.4

### Browser

Firefox 127.0.2

### Client operating system

Linux Elementary OS

### Operating system

Ubuntu 20.04.6 LTS

### Web server

Apache

### PHP engine version

PHP 8.1

### Database

MySQL

**Comment by blizzz** [comment] 2024-07-10 07:17
@barbayellow could you provide the complete log line please? There should be a stack trace.

**Comment by barbayellow** [comment] 2024-07-10 09:40
Here is the full output:

`sudo -u www-data php occ tables:remove 2
An unhandled exception has been thrown:
TypeError: OCA\Tables\Db\Row2Mapper::getFilterExpression(): Argument #2 ($column) must be of type OCA\Tables\Db\Column, null given, called in /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php on line 286 and defined in /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php:310
Stack trace:
#0 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(286): OCA\Tables\Db\Row2Mapper->getFilterExpression()
#1 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(263): OCA\Tables\Db\Row2Mapper->getFilter()
#2 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(241): OCA\Tables\Db\Row2Mapper->getFilterGroups()
#3 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(143): OCA\Tables\Db\Row2Mapper->addFilterToQuery()
#4 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(825): OCA\Tables\Db\Row2Mapper->getWantedRowIds()
#5 /var/www/nextcloud/apps/tables/lib/Service/RowService.php(535): OCA\Tables\Db\Row2Mapper->countRowsForView()
#6 /var/www/nextcloud/apps/tables/lib/Service/ViewService.php(413): OCA\Tables\Service\RowService->getViewRowsCount()
#7 /var/www/nextcloud/apps/tables/lib/Service/ViewService.php(90): OCA\Tables\Service\ViewService->enhanceView()
#8 /var/www/nextcloud/apps/tables/lib/Service/ViewService.php(462): OCA\Tables\Service\ViewService->findAll()
#9 /var/www/nextcloud/apps/tables/lib/Service/TableService.php(420): OCA\Tables\Service\ViewService->deleteAllByTable()
#10 /var/www/nextcloud/apps/tables/lib/Command/RemoveTable.php(67): OCA\Tables\Service\TableService->delete()
#11 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\Tables\Command\RemoveTable->execute()
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#15 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#16 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#17 /var/www/nextcloud/occ(11): require_once('...')
`

**Comment by blizzz** [comment] 2024-07-12 15:31
@barbayellow thank you for reporting =)

Quick fix in https://github.com/nextcloud/tables/pull/1196

**Comment by barbayellow** [comment] 2024-07-15 09:23
Hi thx for the fix. I applied it manually (wget the modified files directly on github + change owner and rights afterwards on our nextcloud instance). Unfortunately, I still have the same error : 

```
sudo -u www-data php /var/www/nextcloud/occ tables:remove 2
An unhandled exception has been thrown:
TypeError: OCA\Tables\Db\Row2Mapper::getFilterExpression(): Argument #2 ($column) must be of type OCA\Tables\Db\Column, null given, called in /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php on line 286 and defined in /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php:310
Stack trace:
#0 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(286): OCA\Tables\Db\Row2Mapper->getFilterExpression()
#1 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(263): OCA\Tables\Db\Row2Mapper->getFilter()
#2 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(241): OCA\Tables\Db\Row2Mapper->getFilterGroups()
#3 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(143): OCA\Tables\Db\Row2Mapper->addFilterToQuery()
#4 /var/www/nextcloud/apps/tables/lib/Db/Row2Mapper.php(825): OCA\Tables\Db\Row2Mapper->getWantedRowIds()
#5 /var/www/nextcloud/apps/tables/lib/Service/RowService.php(535): OCA\Tables\Db\Row2Mapper->countRowsForView()
#6 /var/www/nextcloud/apps/tables/lib/Service/ViewService.php(413): OCA\Tables\Service\RowService->getViewRowsCount()
#7 /var/www/nextcloud/apps/tables/lib/Service/ViewService.php(90): OCA\Tables\Service\ViewService->enhanceView()
#8 /var/www/nextcloud/apps/tables/lib/Service/ViewService.php(462): OCA\Tables\Service\ViewService->findAll()
#9 /var/www/nextcloud/apps/tables/lib/Service/TableService.php(420): OCA\Tables\Service\ViewService->deleteAllByTable()
#10 /var/www/nextcloud/apps/tables/lib/Command/RemoveTable.php(67): OCA\Tables\Service\TableService->delete()
#11 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\Tables\Command\RemoveTable->execute()
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#15 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#16 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#17 /var/www/nextcloud/occ(11): require_once('...')
```
Hope it helps.

**Comment by blizzz** [comment] 2024-07-15 16:17
@barbayellow May I ask how you replaced the files? Also, would you be comfortable running a database query?

**Comment by PlaryWasTaken** [comment] 2024-07-16 17:00
@blizzz I could run a database query, just had this problem happen to me, some users are now unable to load tables and im unable to delete these affected tables

**Comment by barbayellow** [comment] 2024-07-16 18:14
Sûre, I ‘cd’ into the two directories  where files have changed and did a whet on the rough version of the modified file on GitHub. I restored the same right and ownerships as the previous files right after.
No pb to run a database query.  
Le lun. 15 juil. 2024 à 18:17, Arthur Schiwon ***@***.***&gt; a écrit :  @barbayellow May I ask how you replaced the files? Also, would you be comfortable running a database query?

**Comment by blizzz** [comment] 2024-07-18 18:13
@PlaryWasTaken Could you run `select id, filter from oc_tables_views where id = 4;` ?

@barbayellow and could you run `select id, filter from oc_tables_views where table_id = 2;` ?

If there is stuff in the result you do not want public it is totally fine to obfuscate it. Just keep the data types in place, please :)

**Comment by PlaryWasTaken** [comment] 2024-07-18 18:20
> @PlaryWasTaken Could you run `select id, filter from oc_tables_views where id = 4;` ?
> 
> @barbayellow and could you run `select id, filter from oc_tables_views where table_id = 2;` ?
> 
> If there is stuff in the result you do not want public it is totally fine to obfuscate it. Just keep the data types in place, 
I couldnt let the company just stop, so i ended up deleting the offending view directly in the database, although i have the result of the query `select * from oc_tables_views` would that be fine?

**Comment by PlaryWasTaken** [comment] 2024-07-18 18:48
id |       columns       |              sort               |                         filter                          
----+---------------------+---------------------------------+---------------------------------------------------------
  1 | [1,2,3,4]           | []                              | []
  2 | [17,14,15,-4,16,18] | []                              | [[{"columnId":-2,"operator":"is-equal","value":"@me"}]]
  4 | [17,16,18,14,15,-1] | [{"columnId":-4,"mode":"DESC"}] | [[{"columnId":null,"operator":null,"value":""}]]

Heres the result with all the views included and some of the columns removed (But id and filter are still there)

**Comment by blizzz** [comment] 2024-07-19 16:45
@PlaryWasTaken the issue is the empty column in the filter of id 4. This should definitely be fixed with https://github.com/nextcloud/tables/pull/1196 however.

**Comment by blizzz** [comment] 2024-07-22 10:07
> Sure, I pulled the modified files directly from github using wget and copied it in their destination directory. I then gave the ownership back to www-data, gave the according rights, delete the previous files and renamed the newly downloaded files with the original names. No pb to run a database query. We don't have any sensitive data (yet) in the tables application.

Okay, please try this:

1. Revert back to the original files, respectively tables 0.7.4
2. Get the patch: `https://patch-diff.githubusercontent.com/raw/nextcloud/tables/pull/1196.diff`
3. Apply the patch:
    1. `cd /path/to/nextcloud/apps/tables/`
    2. `patch -p1 < /path/to/1196.diff`
4. And retry

**Closed** 2024-07-22 21:03 UTC
Labels: bug, 0. Needs triage
