### ISSUE TITLE
Relational column field -- Select column from another table's column

### ISSUE THREAD

**Issue by 000Shimmy** [nextcloud/tables#802] opened 2024-01-26 04:17 UTC
### Is your feature request related to a problem? Please describe.

No. Enhancement

### Describe the solution you'd like

When constructing a table column, I would like to be able to make the column selection type "Relational" which builds a list from a pre-established table and column. 

Bonus: if more than one column can be used for data validate. 
Ex. instance I have a table called "Customers" with at least three columns "Name"a text field,"Status" a selection between "Lead, Client, etc.", "isActive" a yes/no; and, I have another table called "Projects" where one of the fields is called "Customers" but I want to create rules to validate the options of that Customers.Name to filter [Status] by "Client" and [isActive] by "Yes".  

### Describe alternatives you've considered

Sticking to spreadsheets. 

### Additional context

While this wouldn't make tables a relational database it will add some tremendous functionality and potential. If filtering by multiple columns is not feasible; then perhaps filtering by a single column from a table or a view would add all the functionality required, and then giving views the option to be "hidden" from the sidebar as well as the summary in the main window.

**Comment by enjeck** [comment] 2024-04-14 13:59
Duplicate of https://github.com/nextcloud/tables/issues/172

**Closed by enjeck** 2024-04-14 13:59 UTC
Labels: enhancement, 0. Needs triage
